# Generated by Django 4.2 on 2023-05-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_cartorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='session_key',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
