# Generated by Django 4.2 on 2023-05-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_cartorder_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='quantity',
            new_name='nmb',
        ),
    ]
