# Generated by Django 4.2 on 2023-05-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_page_descriprion_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='page_descriprion',
            new_name='page_description',
        ),
    ]
